# Generated by Django 4.1.3 on 2023-03-03 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_app', '0001_initial'),
        ('medicine_app', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id_workstation', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=300)),
                ('ine_nurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.nursuser')),
                ('ine_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.patientuser')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse_WorkStation',
            fields=[
                ('id_nurs_workstation', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('id_workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_app.workstation')),
                ('ine_nurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.nursuser')),
            ],
        ),
        migrations.CreateModel(
            name='InputRequest',
            fields=[
                ('application_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(max_length=300)),
                ('durg_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.medicine')),
                ('ine_nurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.nursuser')),
            ],
        ),
        migrations.CreateModel(
            name='AttentionOrder',
            fields=[
                ('num_attention', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('attention_time', models.DateTimeField(auto_now=True)),
                ('completed_by', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('num_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient_app.medicalorder')),
            ],
        ),
    ]
